***********************************************************;
*  Demo                                                   *;
*    1) Add a PROC SORT step before PROC PRINT to sort    *;
*       PG1.STORM_FINAL by BasinName and descending       *;
*       MaxWindMPH. Create a temporary table named        *;
*       STORM_SORT. Filter the rows to include only       *;
*       MaxWindMPH>156.                                   *;
*    2) Modify the PROC PRINT step to read the STORM_SORT *;
*       table and group the report by BasinName.          *;
*    3) Add the following title: Category 5 Storms. Clear *;
*       the title for future results.                     *;
*    4) Add labels for the following columns and ensure   *;
*       that PROC PRINT displays the labels:              *;
*       MaxWindMPH => Max Wind (MPH)                      *;
*       MinPressure => Min Pressure                       *;
*       StartDate => Start Date                           *;
*       StormLength => Length of Storm (days)             *;
*    5) Add the NOOBS option in the PROC PRINT statement  *;
*       to suppress the OBS column. Highlight the demo    *;
*       program and run the selected code.                *;
***********************************************************;

***********************************************************;
*  Demo                                                   *;
*    1) Add a PROC SORT step before PROC PRINT to sort    *;
*       PG1.STORM_FINAL by BasinName and descending       *;
*       MaxWindMPH. Create a temporary table named        *;
*       STORM_SORT. Filter the rows to include only       *;
*       MaxWindMPH>156.                                   *;
*    2) Modify the PROC PRINT step to read the STORM_SORT *;
*       table and group the report by BasinName.          *;
*    3) Add the following title: Category 5 Storms. Clear *;
*       the title for future results.                     *;
*    4) Add labels for the following columns and ensure   *;
*       that PROC PRINT displays the labels:              *;
*       MaxWindMPH => Max Wind (MPH)                      *;
*       MinPressure => Min Pressure                       *;
*       StartDate => Start Date                           *;
*       StormLength => Length of Storm (days)             *;
*    5) Add the NOOBS option in the PROC PRINT statement  *;
*       to suppress the OBS column. Highlight the demo    *;
*       program and run the selected code.                *;
***********************************************************;

proc sort data=pg1.storm_final out=storm_sort;
  by BasinName desending MaxWindMPH;
  where MaxWindMPH>156;
run;

title "Category 5 Storms";
proc print=storm_sort label noobs;
   var Season Name MaxWindMPH MinPressure StartDate StormLength;
   by BasinName;
   label MaxWindMPH="Max Wind (MPH)";